{% set name = "bincopy" %}
{% set version = "17.14.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bincopy-{{ version }}.tar.gz
  sha256: 5f4de7c37a3db7adcf3edc4833a223f3356d9bf08be72ec6e431c9f0acd29f18

build:
  number: 1
  noarch: python
  entry_points:
    - bincopy=bincopy:_main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - argparse-addons >=0.4.0
    - humanfriendly
    - pyelftools
    - python >={{ python_min }}

test:
  imports:
    - bincopy
  commands:
    - pip check
    - bincopy --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/eerimoq/bincopy
  summary: Mangling of various file formats that conveys binary information (Motorola S-Record, Intel HEX and binary files).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nisharai1
