{% set name = "bincopy" %}
{% set version = "19.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bincopy-{{ version }}.tar.gz
  sha256: 99b85d541d836010d06f944f46cf474fa7d6852866bad04d0659d9355f838bc2

build:
  number: 0
  noarch: python
  entry_points:
    - bincopy=bincopy:_main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - argparse-addons >=0.4.0
    - humanfriendly
    - pyelftools
    - python >=3.6

test:
  imports:
    - bincopy
  commands:
    - pip check
    - bincopy --help
  requires:
    - pip

about:
  home: https://github.com/eerimoq/bincopy
  summary: Mangling of various file formats that conveys binary information (Motorola S-Record, Intel HEX and binary files).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nisharai1
